### PR TITLE
chore: improve unit test coverage of datetimetypeadapter

### PR DESCRIPTION
**Pull request by Andras-Csanyi**
This PR adds further unit tests against `DateTimeTypeAdapter`, and as a result line coverage goes up over 90%.

Test cases cover null input cases.

### CODE REVIEW

**Review by pyrooka — APPROVED** [review]
There are 2 suggested changes, but it looks good overall.

**Comment by Andras-Csanyi** [comment]
Let's hold off on this PR for a while.

**Review by padamstx — APPROVED** [review]
LGTM

**Pull request merged**
